### 下载文件
GET http://127.0.0.1:10010/file/download?
    filename=/Users/yxy/IdeaProjects/CourseManagerSystem/file/temp/teacher-information-excel-demo.xlsx

### 上传文件
POST http://127.0.0.1:10010/file/upload
Content-Type: multipart/form-data;boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="test.txt"
Content-Type: multipart/form-data

< /Users/yxy/IdeaProjects/CourseManagerSystem/.idea/httpRequests/f.txt
--WebAppBoundary--